#!/usr/bin/env bash
#This script installs and configures a nginx web server
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx restart
